language: d
sudo: false

d:
  # order: latest DMD, oldest DMD, LDC/GDC, remaining DMD versions
  # this way the overall test time gets cut down (GDC/LDC are a lot
  # slower tham DMD, so they should be started early), while still
  # catching most DMD version related build failures early
  - dmd-2.073.0
  - dmd-2.070.2
  - ldc-1.0.0
  - ldc-1.1.0-beta6
  - dmd-2.072.2
  - dmd-2.071.2
  - dmd-beta

matrix:
  exclude:
    - d: ldc-1.0.0
  allow_failures:
    - d: dmd-beta
    - d: ldc-1.1.0-beta6
    - d: ldc-1.0.0
    - d: ldc-1.1.0-beta6

script:
  - dub test --compiler=${DC}

notifications:
  email: false
